
version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/hotel
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:
